routes/web.php
<?php

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::get('statistics', 'DashboardController@statistics')->name('dashboard.statistics');
    //admin users
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'User\UsersController@index')->name('index');
        Route::get('add', 'User\UsersController@create')->name('create');
        Route::post('add', 'User\UsersController@store')->name('store');
        Route::get('accounts', 'User\UserAccountsController@index')->name('accounts.index');
        Route::get('accounts/add', 'User\UserAccountsController@create')->name('accounts.create');
        Route::post('accounts/add', 'User\UserAccountsController@store')->name('accounts.store');
        Route::get('accounts/remove/{id}', 'User\UserAccountsController@delete')->name('accounts.delete');
        Route::get('accounts/edit/{id}', 'User\UserAccountsController@edit')->name('accounts.edit');
        Route::post('accounts/edit/{id}', 'User\UserAccountsController@update')->name('accounts.update');
        Route::get('accounts/search', 'User\UserAccountsController@search')->name('accounts.search');
        Route::get('search', 'User\UsersController@search');
    });
    //admin gateways
    Route::group(['prefix' => 'gateways'], function () {
        Route::get('/', 'Gateway\GatewaysController@index')->name('gateways.index');
        Route::get('add', 'Gateway\GatewaysController@create')->name('gateways.create');
        Route::post('add', 'Gateway\GatewaysController@store')->name('gateways.store');
        Route::get('reports', 'Gateway\ReportsController@index')->name('gateways.reports.index');
        Route::get('search', 'Gateway\GatewaysController@search')->name('gateways.search');

        Route::group(['prefix' => 'plans'], function () {
            Route::get('/', 'Gateway\PlansController@index')->name('gateways.plans.index');
            Route::get('add', 'Gateway\PlansController@create')->name('gateways.plans.create');
            Route::post('add', 'Gateway\PlansController@store')->name('gateways.plans.store');
        });
    });
    //admin withdrawals
    Route::group(['prefix' => 'withdrawals'], function () {
        Route::get('/', 'Withdrawal\WithdrawalsController@index')->name('withdrawals.index');
        Route::get('add', 'Withdrawal\WithdrawalsController@create')->name('withdrawals.create');
        Route::post('add', 'Withdrawal\WithdrawalsController@store')->name('withdrawals.store');
        Route::get('approve/{id}', 'Withdrawal\WithdrawalsController@approve')->name('withdrawals.approve');
        Route::post('approve/{id}',
            'Withdrawal\WithdrawalsController@performApprove')->name('withdrawals.approve.save');
        Route::get('reject/{id}', 'Withdrawal\WithdrawalsController@reject')->name('withdrawals.reject');
    });
    //admin transactions
    Route::group(['prefix' => 'transactions'], function () {
        Route::get('gateway', 'Transaction\GatewayTransactionsController@index')->name('transactions.gateway.index');
        Route::get('bank', 'Transaction\BankTransactionsController@index')->name('transactions.bank.index');
    });
    //admin payments
    Route::group(['prefix' => 'payments'], function () {
        Route::get('/', 'Payment\PaymentsController@index')->name('payments.index');
    });
    //admin settings
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'Setting\SettingsController@index')->name('settings.index');
        Route::get('create', 'Setting\SettingsController@create')->name('settings.create');
        Route::post('create', 'Setting\SettingsController@store')->name('settings.store');
    });

});
Route::group(['namespace' => 'Frontend', 'as' => 'forntend.'], function () {
    Route::get('pay/start', 'PaymentsController@start')->name('payment.start');
    Route::post('pay/verify/{payment_code}', 'PaymentsController@verify')->name('payment.verify');
});

resources/views/partials/errors.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        @foreach($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    </div>
@endif

resources/views/partials/sidebar.blade.php
<div class="right-sidebar">
    <div class="scroll-sidebar">
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="nav-devider"></li>
                <li><a class="has-arrow  " href="#" aria-expanded="false"><i class="fas fa-tachometer-alt"></i>
                        <span
                                class="hide-menu">پیشخوان
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.dashboard.index') }}">وضعیت </a></li>
                        <li><a href="{{ route('admin.dashboard.statistics') }}">آمار </a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-users"></i><span
                                class="hide-menu">کاربران</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.users.index') }}">لیست کاربران</a></li>
                        <li><a href="{{ route('admin.users.create') }}">کاربر جدید</a></li>
                        <li><a href="{{ route('admin.users.accounts.index') }}">حساب های بانکی</a></li>
                        <li><a href="{{ route('admin.users.accounts.create') }}">حساب بانکی جدید</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false">
                        <i class="fas fa-lightbulb"></i>
                        <span
                                class="hide-menu">پلن ها
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.gateways.plans.index') }}">لیست پلن ها</a></li>
                        <li><a href="{{ route('admin.gateways.plans.create') }}">پلن جدید</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false">
                        <i class="far fa-credit-card"></i>
                        <span
                                class="hide-menu">درگاه ها
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.gateways.index') }}">لیست درگاه ها</a></li>
                        <li><a href="{{ route('admin.gateways.create') }}">درگاه جدید</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false">
                        <i class="fas fa-money-bill-alt"></i>
                        <span
                                class="hide-menu">درخواست واریز
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.withdrawals.index') }}">لیست درخواست ها</a></li>
                        <li><a href="{{ route('admin.withdrawals.create') }}">ثبت درخواست</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false">
                        <i class="fas fa-file-excel"></i>
                        <span
                                class="hide-menu">گزارش درگاه
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.gateways.reports.index') }}">لیست گزارش ها</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false">
                        <i class="fas fa-file-invoice-dollar"></i>
                        <span
                                class="hide-menu">تراکنش های درگاه
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.transactions.gateway.index') }}">لیست تراکنش ها</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false">
                        <i class="fas fa-file-invoice-dollar"></i>
                        <span
                                class="hide-menu">تراکنش های بانک
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.transactions.bank.index') }}">لیست تراکنش ها</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false">
                        <i class="fas fa-dollar-sign"></i>
                        <span
                                class="hide-menu">پرداخت ها
                        </span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.payments.index') }}">لیست پرداخت ها</a></li>
                    </ul>
                </li>
                <li><a class="has-arrow  " href="#" aria-expanded="false"><i class="fa fa-cog"></i><span
                                class="hide-menu">تنظیمات</span></a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="{{ route('admin.settings.create') }}">ایجاد</a></li>
                        <li><a href="{{ route('admin.settings.index') }}">لیست</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

resources/views/partials/success.blade.php
@if(session('success'))
    <div class="alert alert-success">
        <p>{{ session('success') }}</p>
    </div>
@endif

resources/views/partials/top_header.blade.php
<div class="header">
    <nav class="navbar top-navbar navbar-expand-md navbar-light">
        <!-- Logo -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ route('admin.dashboard.index') }}">
                <h3>LaraPay</h3>
            </a>
        </div>
        <!-- End Logo -->
        <div class="navbar-collapse">
            <!-- toggle and nav items -->
            <ul class="navbar-nav mr-auto mt-md-0">
                <!-- This is  -->
                <li class="nav-item"><a class="nav-link nav-toggler hidden-md-up text-muted  "
                                        href="javascript:void(0)"><i class="mdi mdi-menu"></i></a></li>
                <li class="nav-item m-l-10"><a class="nav-link sidebartoggler hidden-sm-down text-muted  "
                                               href="javascript:void(0)"><i class="ti-menu"></i></a></li>
            </ul>
            <!-- User profile and search -->
            <ul class="navbar-nav my-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-muted  " href="#" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false"><img src="/images/users/5.jpg" alt="user"
                                                                       class="profile-pic"/></a>
                    <div class="dropdown-menu dropdown-menu-right animated zoomIn">
                        <ul class="dropdown-user">
                            <li><a href="#"><i class="ti-user"></i> پروفایل کاربری</a></li>
                            <li><a href="#"><i class="ti-settings"></i> تننظیمات</a></li>
                            <li><a href="#"><i class="fa fa-power-off"></i> خروج</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>