routes/web.php
<?php

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'as' => 'admin.'], function () {

    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    Route::get('statistics', 'DashboardController@statistics')->name('dashboard.statistics');
    //admin users
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', 'User\UsersController@index')->name('index');
        Route::get('add', 'User\UsersController@create')->name('create');
        Route::post('add', 'User\UsersController@store')->name('store');
        Route::get('accounts', 'User\UserAccountsController@index')->name('accounts.index');
        Route::get('accounts/add', 'User\UserAccountsController@create')->name('accounts.create');
        Route::post('accounts/add', 'User\UserAccountsController@store')->name('accounts.store');
        Route::get('accounts/remove/{id}', 'User\UserAccountsController@delete')->name('accounts.delete');
        Route::get('accounts/edit/{id}', 'User\UserAccountsController@edit')->name('accounts.edit');
        Route::post('accounts/edit/{id}', 'User\UserAccountsController@update')->name('accounts.update');
        Route::get('accounts/search', 'User\UserAccountsController@search')->name('accounts.search');
        Route::get('search', 'User\UsersController@search');
    });
    //admin gateways
    Route::group(['prefix' => 'gateways'], function () {
        Route::get('/', 'Gateway\GatewaysController@index')->name('gateways.index');
        Route::get('add', 'Gateway\GatewaysController@create')->name('gateways.create');
        Route::post('add', 'Gateway\GatewaysController@store')->name('gateways.store');
        Route::get('reports', 'Gateway\ReportsController@index')->name('gateways.reports.index');
        Route::get('search', 'Gateway\GatewaysController@search')->name('gateways.search');

        Route::group(['prefix' => 'plans'], function () {
            Route::get('/', 'Gateway\PlansController@index')->name('gateways.plans.index');
            Route::get('add', 'Gateway\PlansController@create')->name('gateways.plans.create');
            Route::post('add', 'Gateway\PlansController@store')->name('gateways.plans.store');
        });
    });
    //admin withdrawals
    Route::group(['prefix' => 'withdrawals'], function () {
        Route::get('/', 'Withdrawal\WithdrawalsController@index')->name('withdrawals.index');
        Route::get('add', 'Withdrawal\WithdrawalsController@create')->name('withdrawals.create');
        Route::post('add', 'Withdrawal\WithdrawalsController@store')->name('withdrawals.store');
        Route::get('approve/{id}', 'Withdrawal\WithdrawalsController@approve')->name('withdrawals.approve');
        Route::post('approve/{id}',
            'Withdrawal\WithdrawalsController@performApprove')->name('withdrawals.approve.save');
        Route::get('reject/{id}', 'Withdrawal\WithdrawalsController@reject')->name('withdrawals.reject');
    });
    //admin transactions
    Route::group(['prefix' => 'transactions'], function () {
        Route::get('gateway', 'Transaction\GatewayTransactionsController@index')->name('transactions.gateway.index');
        Route::get('bank', 'Transaction\BankTransactionsController@index')->name('transactions.bank.index');
    });
    //admin payments
    Route::group(['prefix' => 'payments'], function () {
        Route::get('/', 'Payment\PaymentsController@index')->name('payments.index');
    });
    //admin settings
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'Setting\SettingsController@index')->name('settings.index');
        Route::get('create', 'Setting\SettingsController@create')->name('settings.create');
        Route::post('create', 'Setting\SettingsController@store')->name('settings.store');
    });

});
Route::group(['namespace' => 'Frontend', 'as' => 'forntend.'], function () {
    Route::get('pay/start', 'PaymentsController@start')->name('payment.start');
    Route::post('pay/verify/{payment_code}', 'PaymentsController@verify')->name('payment.verify');
});

app/Models/Withdrawal.php
<?php

namespace App\Models;

use App\Presenters\Contracts\Presentable;
use App\Presenters\Withdrawal\WithdrawalPresenter;
use Illuminate\Database\Eloquent\Model;

class Withdrawal extends Model
{
    use Presentable;
    const PENDING = 1;
    const DONE = 2;
    const REJECTED = 3;

    protected $primaryKey = 'withdrawal_id';

    protected $guarded = ['withdrawal_id'];

    protected $presenter = WithdrawalPresenter::class;

    /*Relations*/

    public static function getStatuses()
    {
        return [
            self::PENDING  => 'در حال بررسی',
            self::DONE     => 'انجام شده',
            self::REJECTED => 'رد شده'
        ];
    }

    public function gateway()
    {
        return $this->belongsTo(Gateway::class, 'withdrawal_gateway_id');
    }

    /*End Relations*/

    public function account()
    {
        return $this->belongsTo(UserAccount::class, 'withdrawal_user_account_id');
    }

    public function updateStatus($status)
    {
        $this->withdrawal_status = $status;
        $this->save();
    }
}

app/Http/Controllers/Admin/Withdrawal/WithdrawalsController.php
<?php

namespace App\Http\Controllers\Admin\Withdrawal;

use App\Models\Withdrawal;
use App\Repositories\Contracts\GatewayRepositoryInterface;
use App\Repositories\Contracts\WithdrawalRepositoryInterface;
use App\Services\Withdrawal\Validator\WithdrawalValidator;
use App\Services\Withdrawal\WithdrawalRequest;
use App\Services\Withdrawal\WithdrawalService;
use App\ValueObjects\Mobile;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Monolog\Handler\SlackWebhookHandler;

class WithdrawalsController extends Controller
{
    private $withdrawal_service;
    /**
     * @var WithdrawalRepositoryInterface
     */
    private $withdrawalRepository;

    public function __construct(WithdrawalRepositoryInterface $withdrawalRepository)
    {
        $this->withdrawal_service   = new WithdrawalService();
        $this->withdrawalRepository = $withdrawalRepository;
    }

    public function index()
    {
        $withdrawals = $this->withdrawalRepository->all(null, ['gateway', 'account.owner']);

        return view('admin.withdrawal.index', compact('withdrawals'));
    }

    public function create()
    {
        $statuses       = Withdrawal::getStatuses();
        $withdrawalItem = null;

        return view('admin.withdrawal.create', compact('statuses', 'withdrawalItem'));
    }

    public function store(Request $request)
    {
        $gateway_repository = resolve(GatewayRepositoryInterface::class);
        $gateway_item       = $gateway_repository->findWith($request->gateway, ['plan']);
        $gateway_item       = $gateway_item->first();
        $withdrawalRequest  = WithdrawalRequest::fromArray([
            'gateway'    => $request->gateway,
            'account'    => $request->account,
            'amount'     => $request->amount,
            'commission' => $gateway_item->plan->gateway_plan_commission,
            'rate'       => $gateway_item->plan->gateway_plan_withdrawal_rate,
            'max'        => $gateway_item->plan->gateway_plan_withdrawal_max,
            'status'     => $request->status
        ]);
        try {
            $result = $this->withdrawal_service->create($withdrawalRequest);
            if ( ! $result) {
                return back()->withErrors([
                    'error' => 'ثبت درخواست با خطا مواجه شد، لطفا بعدا امتحان کنید'
                ]);
            }

            return redirect()->route('admin.withdrawals.index')->with('success', 'درخواست با موفقیت ثبت شد!');
        } catch (\Exception $exception) {
            //$handler = new SlackWebhookHandler()
            return back()->withErrors([
                'error' => $exception->getMessage()
            ]);
        }

    }

    public function searchGateways(Request $request)
    {

    }

    public function approve(Request $request, $id)
    {
        $withdrawalItem = $this->getById($id);

        return view('admin.withdrawal.approve', compact('withdrawalItem'));

    }

    public function performApprove(Request $request, $id)
    {
//        $withdrawalItem = $this->getById($id);
        $approveResult = $this->withdrawal_service->approve($id, $request->ref_number);
        if ($approveResult) {
            return back()->with('success', 'درخواست با موفقیت تایید شد!');
        }

        return back()->withErrors([
            'error' => 'خطایی درتایید درخواست ایجاد شده است!بعدا امتحان کنید'
        ]);

    }

    public function reject(Request $request, $id)
    {
        $rejectStatus = $this->withdrawal_service->reject($id);
        if ($rejectStatus) {
            return back()->with('success', 'درخواست با موفقیت رد شد!');
        }

        return back()->withErrors([
            'error' => 'رد درخواست نا موفق بود، لطفا بعدا امتحان کنید!'
        ]);
    }

    private function getById($id)
    {
        $withdrawalItem = $this->withdrawalRepository->find($id);
        if ( ! $withdrawalItem) {
            abort(404);
        }

        return $withdrawalItem;
    }
}

resources/views/admin/withdrawal/approve.blade.php
@extends('layouts.admin')
@section('title','تایید درخواست')
@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endsection
@section('content')
    <div class="col-xs-12 col-md-9 col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>تایید درخواست</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        @include('partials.errors')
                        @include('partials.success')
                        <div class="basic-form p-10">
                            <form method="post" action="{{ route('admin.withdrawals.approve.save',[$withdrawalItem->withdrawal_id]) }}"
                                  enctype="multipart/form-data">
                                @include('admin.withdrawal.approve_form')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/withdrawal/approve_form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="ref_number">کد پیگیری :</label>
    <input id="ref_number" name="ref_number" type="text"
           class="form-control input-default">
</div>
<div class="form-group m-t-20">
    <button type="submit" class="btn btn-primary m-b-10 m-l-5">ثبت اطلاعات
    </button>
</div>

resources/views/admin/withdrawal/columns.blade.php
<tr>
    <th>#</th>
    <th>درگاه</th>
    <th>کاربر/اکانت</th>
    <th>مبلغ</th>
    <th>کمیسیون</th>
    <th>شماره پیگیری</th>
    <th>ثبت</th>
    <th>به روز رسانی</th>
    <th>وضعیت</th>
    <th>عملیات</th>
</tr>

resources/views/admin/withdrawal/create.blade.php
@extends('layouts.admin')
@section('title','ثبت درخواست جدید')
@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet"/>
@endsection
@section('content')
    <div class="col-xs-12 col-md-9 col-lg-6">
        <div class="card">
            <div class="card-title">
                <h4>ثبت درخواست جدید</h4>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        @include('partials.errors')
                        @include('partials.success')
                        <div class="basic-form p-10">
                            <form method="post" action="{{ route('admin.withdrawals.store') }}"
                                  enctype="multipart/form-data">
                                @include('admin.withdrawal.form')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
        jQuery(document).ready(function ($) {
            $('#gateway').select2({
                theme: 'classic',
                placeholder: 'جستجوی درگاه ها ...',
                minimumInputLength: 3,
                ajax: {
                    url: '/admin/gateways/search',
                    dataType: 'json',
                    data: function (params) {
                        return {
                            search: params.term,
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data.items,
                        };
                    },
                },
            });
            $('#gateway').on('change', function (e) {

                let currentGateway = $(this).val();
                $('#account').html('');
                $.ajax({
                    type:'GET',
                    url:'{{ route('admin.users.accounts.search') }}',
                    dataType:'json',
                    data:{
                        gateway:currentGateway
                    },
                    success:function(response){
                        let items = response.items;
                       items.forEach(function(item){
                            $('#account').append('<option value="'+item.id+'">'+item.text+'</option>');
                       });
                    },
                    error:function(error){}
                });
            });
        });
    </script>
@endsection

resources/views/admin/withdrawal/form.blade.php
{{ csrf_field() }}
<div class="form-group">
    <label for="gateway"> درگاه :</label>
    <select name="gateway" id="gateway" class="form-control input-default"></select>
</div>
<div class="form-group">
    <label for="account"> حساب :</label>
    <select name="account" id="account" class="form-control input-default"></select>
</div>

<div class="form-group">
    <label for="amount">مبلغ :</label>
    <input id="amount" name="amount" type="text"
           class="form-control input-default"
           value="{{ old('amount',!is_null($withdrawalItem) ? $withdrawalItem->user_account_title:'') }}">
</div>
<div class="form-group">
    <label for="status">وضعیت :</label>
    <select name="status" id="status" class="form-control">
        @foreach($statuses as $status => $title)
            <option value="{{ $status }}" {{ !is_null($withdrawalItem) && $withdrawalItem->user_account_status == $status ? 'selected' : ''  }}>{{ $title }}</option>
        @endforeach
    </select>
</div>
<div class="form-group m-t-20">
    <button type="submit" class="btn btn-primary m-b-10 m-l-5">ثبت اطلاعات
    </button>
</div>

resources/views/admin/withdrawal/index.blade.php
@extends('layouts.admin')
@section('title')لیست درخواست های واریز@endsection
@section('content')
    <div class="col-lg-12">
        <div class="card">
            <div class="card-title">
                <h4>لیست درخواست های واریز </h4>
            </div>
            <div class="card-body">
                @include('partials.errors')
                @include('partials.success')
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            @include('admin.withdrawal.columns')
                        </thead>
                        <tbody>
                            @each('admin.withdrawal.item',$withdrawals,'withdrawal')
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/withdrawal/item.blade.php
<tr>
    <td scope="row">{{ $withdrawal->withdrawal_id }}</td>
    <td>{{ $withdrawal->gateway->gateway_title }}</td>
    <td>{{ $withdrawal->account->user_account_title .'/'. $withdrawal->account->owner->name }}</td>
    <td>{{ $withdrawal->present()->amount }}</td>
    <td>{{ $withdrawal->present()->commission }}</td>
    <td>{{ $withdrawal->withdrawal_ref_number }}</td>
    <td>{{ $withdrawal->present()->create }}</td>
    <td>{{ $withdrawal->present()->update }}</td>
    <td>{!!  $withdrawal->present()->adminStatus !!}</td>
    <td>
       {!!  $withdrawal->present()->adminOperations !!}
    </td>
</tr>

resources/views/admin/withdrawal/operations.blade.php
<a class="btn btn-success btn-xs" href="{{ route('admin.withdrawals.approve',[$withdrawal->withdrawal_id]) }}">تایید</a>
<a class="btn btn-danger btn-xs"
   href="{{ route('admin.withdrawals.reject',[$withdrawal->withdrawal_id]) }}">رد</a>